### ISSUE TITLE
problem with import node:net

### ISSUE THREAD

**Issue by Areen3** [sindresorhus/is-port-reachable#12]
I have problem with build my code in monorepo (nx.dev) that use Yours npm
problem comes form import: 

import net from 'node:net';

when I  change it on const net = require('node:net'); -> https://nodejs.org/api/net.html#net
or import * as net from 'net';
webpack works ok

can You change way of import ?

**Comment by Areen3** [comment]
error with log was:
`E:\temp\to-check-something\microsrv\node_modules\.pnpm\@nrwl+js@15.7.2_l2go343goxpltaofgvb3j3yxpy\node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js:16
        return originalLoader.apply(this, arguments);
                              ^
Error [ERR_REQUIRE_ESM]: require() of ES Module E:\temp\to-check-something\microsrv\node_modules\.pnpm\is-port-reachable@4.0.0\node_modules\is-port-reachable\index.js from E:\temp\to-check-something\microsrv\dist\apps\app\main.js not supported.
Instead change the require of index.js in E:\temp\to-check-something\microsrv\dist\apps\app\main.js to a dynamic import() which is available in all CommonJS modules.
    at Module._load (E:\temp\to-check-something\microsrv\node_modules\.pnpm\@nrwl+js@15.7.2_l2go343goxpltaofgvb3j3yxpy\node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js:16:31)
    at is-port-reachable (E:\temp\to-check-something\microsrv\dist\apps\app\main.js:1251:18)
    at __webpack_require__ (E:\temp\to-check-something\microsrv\dist\apps\app\main.js:1310:41)
    at E:\temp\to-check-something\microsrv\dist\apps\app\main.js:1331:29
    at E:\temp\to-check-something\microsrv\dist\apps\app\main.js:1355:3
    at Object.<anonymous> (E:\temp\to-check-something\microsrv\dist\apps\app\main.js:1360:12)
    at Module._load (E:\temp\to-check-something\microsrv\node_modules\.pnpm\@nrwl+js@15.7.2_l2go343goxpltaofgvb3j3yxpy\node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js:16:31)
    at Object.<anonymous> (E:\temp\to-check-something\microsrv\node_modules\.pnpm\@nrwl+js@15.7.2_l2go343goxpltaofgvb3j3yxpy\node_modules\@nrwl\js\src\executors\node\node-with-require-overrides.js:19:1)
`

**Comment by sindresorhus** [comment]
https://gist.github.com/sindresorhus/a39789f98801d908bbc7ff3ecc99d99c
